find_lover:
    resource: "@FindLoverBundle/Controller/"
    type:     annotation
    prefix:   /

find_lover_logout:
    path: /logout

find_lover_api:
    resource: "@FindLoverApiBundle/Controller/"
    type:     annotation
    prefix:   /api
