<?php

namespace FindLoverBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use FindLoverBundle\Entity\Friendship;
use FindLoverBundle\Entity\Lover;

/**
 * FriendshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendshipRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int|string $currentUserId
     *
     * @return Lover[]|null|[]
     */
    public function findRecentlyAvailable($currentUserId)
    {
        $sql = "
            SELECT REGEXP_REPLACE(participants, '(, $currentUserId|$currentUserId, )', '') as id 
            FROM friendship as f 
            WHERE f.participants LIKE :id
        ";

        $statement = $this->getEntityManager()->getConnection()->prepare($sql);
        $statement->bindValue('id', "%$currentUserId%");
        $statement->execute();
        $friendsIds = array_column($statement->fetchAll(), 'id');

        $friendsAvailable = $this->getEntityManager()
                                 ->getRepository('FindLoverBundle:Lover')
                                 ->createQueryBuilder('l')
                                 ->select('l.id', 'l.firstName', 'l.lastName', 'l.nickname', 'l.profilePicture', 'l.lastOnline')
                                 ->where('l.id IN (:ids)')
                                 ->andWhere("l.lastOnline is NULL")
                                 ->orWhere("l.lastOnline >= :datePrevHour")
                                 ->setParameters(
                                     array(
                                         'ids' => $friendsIds,
                                         'datePrevHour' => date('Y-m-d H:i:s', strtotime('-1 hour'))
                                     )
                                 )
                                 ->getQuery()
                                 ->getResult();

        return $friendsAvailable;

    }
}
