<?php

namespace FindLoverBundle\Repository;

use FindLoverBundle\Entity\Invitation;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string|int $participant
     *
     * @return Invitation[]
     */
    public function findInvitationsReceived($participant)
    {
        return $this->createQueryBuilder('i')
            ->where('i.participants LIKE :participant')
            ->setParameter('participant', "%$participant")
            ->getQuery()
            ->getResult();
    }
}
