<?php

namespace FindLoverBundle\Repository;

/**
 * LoverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoverRepository extends \Doctrine\ORM\EntityRepository
{
}
