lover_topic_chat:
    channel: lover/channel/{participants}
    handler:
        callback: "find_lover.topic"
    requirements:
        participants:
            path: "[0-9]+-[0-9]+"

lover_topic_state:
    channel: lover/login
    handler:
        callback: "lover_topic_state.topic"
